import { notFound } from "next/navigation";
import { APPLICATION_STATUSES } from "@/lib/creator-applications";
import { getApplicationForAdmin, listApplicationAssetsForOne, listApplicationReviewNotes } from "@/lib/creator-application-admin";

export const dynamic = "force-dynamic";

function label(value: string) { return value.toLowerCase().replaceAll("_", " ").replace(/\b\w/g, (m) => m.toUpperCase()); }
function list(value?: string[]) { return value?.length ? value.join(", ") : "—"; }
function bytes(value: number) { return value < 1_000_000 ? `${Math.max(1, Math.round(value/1000))} KB` : `${(value/1_000_000).toFixed(1)} MB`; }
function yesNo(value?: boolean) { return value ? "Yes" : "No"; }

export default async function ApplicationDetailPage({ params, searchParams }: { params: Promise<{ applicationId: string }>; searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const { applicationId } = await params;
  const query = await searchParams;
  const [application, assets, notes] = await Promise.all([getApplicationForAdmin(applicationId), listApplicationAssetsForOne(applicationId), listApplicationReviewNotes(applicationId)]);
  if (!application) notFound();
  const data = application.data || {};
  const convertible = ["APPROVED","BUILDING","CREATOR_REVIEW","PUBLISHED"].includes(application.status);

  return <div className="workspace-page">
    <style>{`
      .review-head-actions{display:flex;gap:8px;flex-wrap:wrap}.review-layout{display:grid;grid-template-columns:1.3fr .7fr;gap:14px}.review-section{border:1px solid var(--line);border-radius:17px;padding:17px;background:rgba(255,255,255,.02);margin-bottom:12px}.review-section h2{margin:0 0 13px;font-size:1.08rem}.review-fields{display:grid;grid-template-columns:1fr 1fr;gap:11px}.review-field{border:1px solid var(--line);border-radius:12px;padding:11px}.review-field small{display:block;color:var(--dim);margin-bottom:5px}.review-field p{margin:0;white-space:pre-wrap;color:var(--muted);line-height:1.55}.review-wide{grid-column:1/-1}.review-tags{display:flex;flex-wrap:wrap;gap:6px}.review-tags span{padding:5px 8px;border:1px solid var(--line);border-radius:999px;font-size:.75rem;color:var(--muted)}.asset-stack,.note-stack{display:grid;gap:8px}.asset-item{display:flex;justify-content:space-between;gap:12px;align-items:center;border:1px solid var(--line);border-radius:12px;padding:11px}.note-item{border:1px solid var(--line);border-radius:12px;padding:12px}.note-item header{display:flex;justify-content:space-between;gap:12px;margin-bottom:6px}.note-item p{white-space:pre-wrap;margin:0;color:var(--muted);line-height:1.55}.side-actions{position:sticky;top:18px}.side-actions form{display:grid;gap:9px;margin-top:12px}.side-actions select,.side-actions textarea{background:var(--surface-2);color:var(--text);border:1px solid var(--line);border-radius:11px;padding:11px;font:inherit}.score{font-size:2.5rem;font-weight:850;letter-spacing:-.04em}.meta-line{color:var(--muted);line-height:1.6}.success-note{padding:11px 13px;border-radius:11px;background:rgba(39,215,167,.07);color:#8ef2d0;border:1px solid rgba(39,215,167,.25);margin-bottom:12px}@media(max-width:900px){.review-layout{grid-template-columns:1fr}.side-actions{position:static}.review-fields{grid-template-columns:1fr}.review-wide{grid-column:1}}
    `}</style>
    <header className="page-head"><div><span className="eyebrow">APPLICATION REVIEW</span><h1>{application.creatorName || application.fullName}</h1><p>{application.fullName} · {application.email} · {application.id}</p></div><div className="review-head-actions"><a className="button secondary compact" href="/app/applications">← Applications</a><a className="button secondary compact" href={`/app/applications/${application.id}/brief`}>Production brief</a><a className="button secondary compact" href={`mailto:${application.email}?subject=${encodeURIComponent("Your HPEDIT creator portfolio application")}`}>Email creator</a></div></header>
    {query.noted ? <div className="success-note">Review note saved.</div> : null}

    <div className="review-layout"><main>
      <section className="review-section"><h2>Identity & positioning</h2><div className="review-fields"><div className="review-field"><small>Full name</small><p>{application.fullName}</p></div><div className="review-field"><small>Creator / stage name</small><p>{application.creatorName || "—"}</p></div><div className="review-field"><small>Category</small><p>{application.primaryCategory || "—"}</p></div><div className="review-field"><small>Secondary niches</small><p>{list(data.secondaryCategories)}</p></div><div className="review-field"><small>Location</small><p>{[data.city,data.state,data.country].filter(Boolean).join(", ") || "—"}</p></div><div className="review-field"><small>Languages</small><p>{list(data.languages)}</p></div><div className="review-field review-wide"><small>Headline</small><p>{data.headline || "—"}</p></div><div className="review-field review-wide"><small>Bio / creator story</small><p>{data.bio || "—"}</p></div></div></section>
      <section className="review-section"><h2>Contact & social presence</h2><div className="review-fields"><div className="review-field"><small>Email</small><p>{data.email || application.email}</p></div><div className="review-field"><small>Phone / WhatsApp</small><p>{[data.phone,data.whatsapp].filter(Boolean).join(" · ") || "—"}</p></div><div className="review-field"><small>Instagram</small><p>{data.instagram || "—"}</p></div><div className="review-field"><small>YouTube</small><p>{data.youtube || "—"}</p></div><div className="review-field"><small>Facebook</small><p>{data.facebook || "—"}</p></div><div className="review-field"><small>LinkedIn</small><p>{data.linkedin || "—"}</p></div><div className="review-field review-wide"><small>Other social profiles</small><p>{data.otherSocials || "—"}</p></div></div></section>
      <section className="review-section"><h2>Audience & performance</h2><div className="review-fields"><div className="review-field"><small>Followers / subscribers</small><p>{data.followers?.toLocaleString?.() || "—"}</p></div><div className="review-field"><small>Monthly reach</small><p>{data.monthlyReach?.toLocaleString?.() || "—"}</p></div><div className="review-field"><small>Typical views</small><p>{data.averageViews?.toLocaleString?.() || "—"}</p></div><div className="review-field"><small>Audience notes</small><p>{data.audienceNotes || "—"}</p></div></div></section>
      <section className="review-section"><h2>Commercial work & goals</h2><div className="review-fields"><div className="review-field review-wide"><small>Notable collaborations</small><p>{data.notableCollaborations || "—"}</p></div><div className="review-field review-wide"><small>Achievements / press</small><p>{data.achievements || "—"}</p></div><div className="review-field review-wide"><small>Services offered</small><div className="review-tags">{data.services?.length ? data.services.map((item)=><span key={item}>{item}</span>) : <span>None selected</span>}</div></div><div className="review-field review-wide"><small>12-month goals</small><div className="review-tags">{data.goals?.length ? data.goals.map((item)=><span key={item}>{item}</span>) : <span>None selected</span>}</div></div><div className="review-field review-wide"><small>HPEDIT opportunities / needs</small><div className="review-tags">{data.hpeditNeeds?.length ? data.hpeditNeeds.map((item)=><span key={item}>{item}</span>) : <span>None selected</span>}</div></div></div></section>
      <section className="review-section"><h2>Portfolio preferences & permissions</h2><div className="review-fields"><div className="review-field"><small>Visual style</small><p>{data.preferredStyle || "—"}</p></div><div className="review-field"><small>Colours</small><p>{data.preferredColours || "—"}</p></div><div className="review-field"><small>Show audience metrics</small><p>{yesNo(data.showAudienceMetrics)}</p></div><div className="review-field"><small>Show rates</small><p>{yesNo(data.showRates)}</p></div><div className="review-field"><small>Public email</small><p>{yesNo(data.publicEmail)}</p></div><div className="review-field"><small>Public WhatsApp</small><p>{yesNo(data.publicWhatsapp)}</p></div><div className="review-field review-wide"><small>Additional notes</small><p>{data.additionalNotes || "—"}</p></div><div className="review-field"><small>Portfolio content consent</small><p>{yesNo(data.consentPortfolio)}</p></div><div className="review-field"><small>Privacy acknowledgement</small><p>{yesNo(data.consentPrivacy)}</p></div><div className="review-field"><small>Marketing consent</small><p>{yesNo(data.consentMarketing)}</p></div><div className="review-field"><small>Email verification</small><p>{application.emailVerifiedAt ? `Verified ${application.emailVerifiedAt.toLocaleString("en-IN")}` : "Not verified yet"}</p></div></div></section>
      <section className="review-section"><h2>Submitted material · {assets.length}</h2>{assets.length ? <div className="asset-stack">{assets.map((asset)=><div className="asset-item" key={asset.id}><div><strong>{asset.fileName}</strong><div className="meta-line">{label(asset.kind)} · {bytes(asset.size)} · {asset.contentType}</div></div><a className="button secondary compact" href={`/api/creator-applications/assets/admin/${asset.id}`} target="_blank">Open</a></div>)}</div> : <p className="meta-line">No files attached.</p>}</section>
      <section className="review-section"><h2>Review timeline · {notes.length}</h2>{notes.length ? <div className="note-stack">{notes.map((note)=><article className="note-item" key={note.id}><header><strong>{label(note.noteType)}</strong><span className="meta-line">{note.createdAt.toLocaleString("en-IN")}</span></header><p>{note.body}</p></article>)}</div> : <p className="meta-line">No reviewer notes yet.</p>}</section>
    </main>

    <aside><section className="panel side-actions"><span className={`status ${application.status === "PUBLISHED" ? "active" : application.status === "SUBMITTED" ? "review" : "planning"}`}>{label(application.status)}</span><div className="score">{application.completion}%</div><div className="meta-line">Portfolio readiness<br/>Created {application.createdAt.toLocaleString("en-IN")}<br/>Updated {application.updatedAt.toLocaleString("en-IN")}</div>
      {application.status !== "DRAFT" ? <form action="/api/creator-applications/manage" method="post"><input type="hidden" name="id" value={application.id}/><label>Status<select name="status" defaultValue={application.status}>{APPLICATION_STATUSES.filter((s)=>s!=="DRAFT").map((s)=><option key={s} value={s}>{label(s)}</option>)}</select></label><button className="button primary" type="submit">Update application</button></form> : null}
      <form action="/api/creator-applications/notes" method="post"><input type="hidden" name="applicationId" value={application.id}/><label>Note type<select name="noteType" defaultValue="INTERNAL_NOTE"><option value="INTERNAL_NOTE">Internal note</option><option value="REQUEST_INFO">Request information</option><option value="DECISION">Decision</option><option value="FOLLOW_UP">Follow-up</option></select></label><label>Reviewer note<textarea name="body" rows={5} required placeholder="Record the decision, missing information, follow-up or context…"/></label><button className="button secondary" type="submit">Save review note</button><small className="meta-line">“Request information” also moves the application to Info Required. It does not automatically email the creator.</small></form>
      {convertible ? <form action="/api/creator-applications/convert" method="post"><input type="hidden" name="id" value={application.id}/><button className="button secondary" type="submit">Create / refresh Creator record</button></form> : null}
    </section></aside></div>
  </div>;
}
